### ISSUE TITLE
Module build error(Angular5)

### ISSUE THREAD

**Issue by jackzhum** [aspnetboilerplate/abp-ng2-module#18] opened 2018-02-11 06:27 UTC
ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: D:\Projects\Huabo.ERP\angular-alain\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by ismcagdas** [comment] 2018-02-11 19:44
@jackzhum what is your angular verison ? 
Are you using one of ABP Templates ?

**Comment by jackzhum** [comment] 2018-02-12 00:10
@ismcagdas  angular 5

**Comment by ismcagdas** [comment] 2018-02-12 05:35
@jackzhum sorry, I wanted to know exact version. Is it 5.2.4 ?

**Comment by jackzhum** [comment] 2018-02-12 08:48
@ismcagdas The latest version

**Comment by jackzhum** [comment] 2018-02-12 08:50
@ismcagdas 
`{
  "name": "myproject",
  "version": "0.6.6",
  "description": "myproject",
  "author": "cipchk",
  "homepage": "",  
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  },
  "license": "MIT",
  "scripts": {
    "precommit": "npm run lint-staged",
    "ng": "ng",
    "start": "ng serve -o",
    "serve:hmr": "ng serve -o --hmr -e=hmr",
    "build": "ng build --prod --build-optimizer",
    "analyze": "ng build --prod --build-optimizer --stats-json",
    "lint": "run-s lint:ts lint:style",
    "lint:ts": "ng lint",
    "lint:style": "stylelint \"{src}/**/*.less\" --syntax less",
    "lint-staged": "lint-staged",
    "e2e": "ng e2e",
    "test": "ng test -sr -sm=false",
    "test-coverage": "ng test -sr -cc -sm=false"
  },
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@antv/data-set": "^0.8.3",
    "@antv/g2": "^3.0.1",
    "@antv/g2-plugin-slider": "^2.0.0",
    "@delon/abc": "^0.6.5",
    "@delon/acl": "^0.6.5",
    "@delon/auth": "^0.6.5",
    "@delon/theme": "^0.6.5",
    "@delon/mock": "^0.6.5",
    "@delon/cache": "^0.6.5",
    "@ngx-translate/core": "^9.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "angular-baidu-maps": "^1.0.1",
    "angular-qq-maps": "^1.0.1",
    "angular-split": "^1.0.0-rc.0",
    "angular-tree-component": "^7.0.1",
    "core-js": "^2.5.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "moment": "^2.19.3",
    "ng-clipboard-antd": "^2.0.1",
    "ng-tree-antd": "^2.2.2",
    "ng-zorro-antd": "^0.6.5",
    "ng-zorro-antd-extra": "^1.1.6",
    "ng2-dnd": "^5.0.0",
    "ng2-img-cropper": "^0.9.0",
    "ngx-color-picker": "^5.0.0",
    "ngx-countdown": "^2.0.0",
    "ngx-tinymce": "^1.0.1",
    "ngx-ueditor": "^1.1.0",
    "rxjs": "^5.5.5",
    "screenfull": "^3.3.1",
    "simple-line-icons": "^2.4.1",
    "sweetalert2": "^7.0.0",
    "weather-icons": "^1.3.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.2",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "@delon/cli": "^0.6.4",
    "@types/jasmine": "~2.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jszip": "^3.1.2",
    "@types/node": "~6.0.60",
    "codecov": "^3.0.0",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sauce-launcher": "^1.2.0",
    "lint-staged": "^5.0.0",
    "npm-run-all": "^4.1.1",
    "protractor": "~5.1.2",
    "stylelint": "^8.2.0",
    "stylelint-config-standard": "^17.0.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "mockjs": "^1.0.1-beta3",
    "@types/mockjs": "^1.0.0",
    "xlsx": "^0.11.16"
  },
  "lint-staged": {
    "src/**/*.ts": "lint:ts",
    "src/**/*.less": "lint:style"
  }
}
`

**Comment by ismcagdas** [comment] 2018-02-12 08:53
Thanks @jackzhum, I will check it according to latest version.

**Comment by jackzhum** [comment] 2018-02-12 08:56
Thanks @ismcagdas .
![qq 20180212165224](https://user-images.githubusercontent.com/15189709/36089193-8f3db398-1015-11e8-99a1-b2e70f542f13.jpg)

**Comment by Y2zz** [comment] 2018-02-14 07:47
I have encountered this problem, currently unable to import angular5

**Comment by ismcagdas** [comment] 2018-02-15 07:07
@Y2zz are you using v2.0 or v1.3 ?

**Comment by Y2zz** [comment] 2018-02-15 07:09
@ismcagdas  using V2.0

**Comment by ismcagdas** [comment] 2018-02-15 07:15
@Y2zz using v2.0 is different than v1.3 because we replaced Angular's Http with HttpClient.
I suggest you to remove node_modules folder and install it from scratch using "yarn".

If you still have problems, please share error message with your code.

**Comment by Y2zz** [comment] 2018-02-15 07:28
My situation is like this, a new angular project, the implementation of npm install abp-ng2-module abp-web-resources can not be imported in the module, typescript prompt does not recognize the module

**Comment by ismcagdas** [comment] 2018-02-15 08:38
@Y2zz I have just tried with latest angular-cli (1.6.8) and it worked for me when I followed below steps.

1. Create a new angular app using "ng new myApp" command.
2. Then run "npm install abp-ng2-module" and "npm install abp-web-resources" commands.
3. import abp module in the app module like below;

`import { AbpModule } from '../../node_modules/abp-ng2-module/src/abp.module';`

and use it in app module's imports like below;
```
imports: [
    BrowserModule,
    AbpModule
  ]
```

4. Finally add below lines into typings.d.ts file;

```
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/abp.d.ts"/>
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/libs/abp.jquery.d.ts"/>
///<reference path="../node_modules/abp-web-resources/Abp/Framework/scripts/libs/abp.signalr.d.ts"/>
```

**Comment by ismcagdas** [comment] 2018-02-15 08:55
@jackzhum are you working on the ABP template ?

**Comment by ismcagdas** [comment] 2018-02-17 11:14
@Y2zz @jackzhum did you have a chance to try this ?

**Comment by Y2zz** [comment] 2018-02-19 14:25
@ismcagdas  I tried, eventually migrating abp-ng2-module code into actual projects to take effect

**Comment by Y2zz** [comment] 2018-02-19 14:29
@jackzhum 新年好，我最终是把 abp-ng2-module 中的代码迁移到了项目中，npm引用会出现找不到模块。具体不知道是因为 abp-ng2-module 中的版本对不上还是什么情况，总之在VSCode中无法代码提示

**Comment by Y2zz** [comment] 2018-02-21 15:48
@ismcagdas  Currently my question is consistent with @jackzhum

```
ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: D:\Develop\Projects\Angular\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/abp-ng2-module/src/abpHttpInterceptor.ts
Module build failed: Error: D:\Develop\Projects\Angular\node_modules\abp-ng2-module\src\abpHttpInterceptor.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/abp-ng2-module/src/auth/permission-checker.service.ts
Module build failed: Error: D:\Develop\Projects\Angular\node_modules\abp-ng2-module\src\auth\permission-checker.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/abp-ng2-module/src/features/feature-checker.service.ts
Module build failed: Error: D:\Develop\Projects\Angular\node_modules\abp-ng2-module\src\features\feature-checker.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/abp-ng2-module/src/localization/localization.service.ts
Module build failed: Error: D:\Develop\Projects\Angular\node_modules\abp-ng2-module\src\localization\localization.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\Develop\Projects\Angular\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/abp-ng2-module/src/multi-tenancy/abp-multi-tenancy.service.ts
M
```

**Comment by ismcagdas** [comment] 2018-02-22 06:08
@Y2zz can you share your project's source code ? I think it will be easier to find the problem like that.

**Comment by Y2zz** [comment] 2018-02-22 06:15
@ismcagdas  I use https://github.com/cipchk/ng-alain as a template and reference abp-ng2-module

**Comment by ismcagdas** [comment] 2018-02-22 06:26
Thanks, I will check it.

**Comment by Y2zz** [comment] 2018-02-22 07:04
@ismcagdas  This is my demo code https://github.com/Y2zz/test_alain_abp

**Comment by ismcagdas** [comment] 2018-02-23 07:26
@Y2zz thanks for sharing. When I changed
```
"lib": [
      "es2017",
      "dom"
    ]
```

to

```
"lib": [
      "es6",
      "dom"
    ]
```

the error goes away but there is another error like below. I thin you can fix it by using lodash or a similar library.

> ERROR in src/app/core/i18n/i18n.service.ts(26,30): error TS2339: Property 'includes' does not exist on type 'string[]'.

**Comment by Y2zz** [comment] 2018-02-23 07:28
@ismcagdas Alright, thank you。 I will try again

**Comment by flexem** [comment] 2018-02-24 02:09
Hi @ismcagdas 
Here's an in-depth explanation why this happend.
https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325.

I think we should use the files in "dist/src" not the "src".

By the way.The dist you published to npm was wrong.Did you foget to update it?
In my project it tells me "Cannot find module '@abp/abpHttpInterceptor'".
I checked the files in "node_modules\abp-ng2-module\dist\src",  there's no abpHttpInterceptor files.

**Comment by ismcagdas** [comment] 2018-02-24 11:05
Thanks @flexem I will fix it.

**Comment by jackzhum** [comment] 2018-03-03 13:41
Hi @ismcagdas 
Excuse me, is there any plan to upgrade to es2017？

**Comment by ismcagdas** [comment] 2018-03-07 06:58
@jackzhum we don't have such a plan for now. Can you explain what is the benefit of upgrading to es2017 ?

**Comment by iyhammad** [comment] 2018-03-12 14:18
I'm facing this issue right now. 
the exact error is below 
```
ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: C:\path\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\path\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\path\node_modules\@ngtools\webpack\src\loader.js:467:39)    at process._tickCallback (internal/process/next_tick.js:109:7)
```
Angular: 5.2.8
Angular/cli: 1.7.3
Is there a workaround for this?.
Thanks,

**Comment by ismcagdas** [comment] 2018-03-12 14:20
@iyhammad have you tried this https://github.com/aspnetboilerplate/abp-ng2-module/issues/18#issuecomment-367931144 ? Are you using v2.0 or v2.1 ?

**Comment by iyhammad** [comment] 2018-03-12 14:32
@ismcagdas I'm on v2.1 and my tsconfig is already like https://github.com/aspnetboilerplate/abp-ng2-module/issues/18#issuecomment-367931144 
I've added this to my tsconfig and it resolved the issue but i'm not sure if this is the best workaround.
```
  "include": [
    "../src/**/*",
    "../node_modules/abp-ng2-module/src/**/*"
  ],
```

**Comment by ismcagdas** [comment] 2018-03-12 14:33
@iyhammad you can use it like that for now.

**Comment by brunobertechini** [comment] 2018-03-26 17:31
Same issue here trying to add abp to new angular-cli project. 

```
ng new abp-angular-cli
yarn add abp-web-resources@3.2.3
yarn add abp-ng2-module@2.0.0
```
```
warning "abp-ng2-module > @angular/http@5.2.9" has incorrect peer dependency "@angular/platform-browser@5.2.9".
```

After importing into AppModule:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/abp-ng2-module/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

**Comment by brunobertechini** [comment] 2018-03-26 18:27
Note: After upgrading to Angular 5.2.9 -> everything compiled successfully

**Comment by ismcagdas** [comment] 2018-03-27 05:46
@iyhammad @Y2zz @flexem can you also try this ?

**Comment by Y2zz** [comment] 2018-03-27 05:48
Okay, I'll try later

**Comment by iyhammad** [comment] 2018-03-27 06:09
I can confirm It's working after Angular upgrade to 5.2.9

**Comment by ismcagdas** [comment] 2018-03-27 06:30
I'm closing this issue then.

**Closed by ismcagdas** 2018-03-27 06:30 UTC
Labels: problem

**Comment by Worthy7** [comment] 2018-04-02 05:03
I'm having this problem still even on the latest angular.

**Comment by Worthy7** [comment] 2018-04-02 05:25
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "baseUrl": ".",
    "paths": {
      "@abp/*": [ "../node_modules/abp-ng2-module/src/*" ],
      "@app/*": [ "./app/*" ],
      "@shared/*": [ "./shared/*" ],
      "@node_modules/*": [ "../node_modules/*" ]
    }
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "../src/**/*",
    "../node_modules/abp-ng2-module/src/**/*"
  ]
}
```

**Comment by ismcagdas** [comment] 2018-04-03 07:08
@Worthy7 thanks. We use it like that as well. Why do you think it is wrong ?

**Comment by Worthy7** [comment] 2018-04-03 07:41
Well, because the files in 
"../node_modules/abp-ng2-module/src/**/*"
should be managed by the ts config in abp-ng2-module. We shouldn't have to manually add the include to our projects tsconfig.

**Comment by ismcagdas** [comment] 2018-04-03 07:43
So, should it be "../node_modules/abp-ng2-module/dist/**/*" instead ?

**Comment by Worthy7** [comment] 2018-04-03 07:50
I don't know, I'm not an expert here, but I feel that forcing us to put 
```
"include": [
    "../src/**/*",
    "../node_modules/abp-ng2-module/src/**/*"
  ]
```
into *out* tsconfig, is a hack and not a fix.
I think that *at least* this should be inside node_modules/abp-ng1-module/tsconfig.json instead. But even then, I don't understand why it is not seeing `abp-user-configuration.service.ts` automatically

**Comment by ismcagdas** [comment] 2018-04-05 06:38
@Worthy7 I have created an issue https://github.com/aspnetboilerplate/abp-ng2-module/issues/23. Let us think on this again.

**Comment by LegolasTheElves** [comment] 2018-04-11 11:10
I also facing the same problem I am currently following the tutorial in Angular Tutorial: Tour of Heroes
yesterday all were running smooth but just early this day when running the ng serve the error show ERROR in ./src/app/hero.ts
Module build failed: Error: D:\angular-tour-of-heroes\src\app\hero.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

I already try some of the suggested solutions but nothing happen anyone can help me out on this

**Comment by ismcagdas** [comment] 2018-04-11 11:15
@LegolasTheElves it seems like your problem is not related to abp-ng2-module. Are you using https://github.com/aspnetboilerplate/module-zero-core-template ?

**Comment by LegolasTheElves** [comment] 2018-04-11 11:29
@ismcagdas nope I am new in angular I'm just currently following this tutorial https://angular.io/tutorial/toh-pt3

**Comment by ismcagdas** [comment] 2018-04-11 11:31
@LegolasTheElves then you should create your issue on https://github.com/angular/angular.

**Comment by sebfischer83** [comment] 2018-04-11 14:57
I´m facing the same error
`ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: C:\Projekte\Cointo\CointoWeb\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

try all solutions here but doesn't help me.
It appears after updating from Angular 5.0.0 to 5.2.9

**Comment by Worthy7** [comment] 2018-04-12 00:10
@sebfischer83 make sure you have all your packages installed properly, `yarn install`

**Comment by ismcagdas** [comment] 2018-04-12 07:02
@sebfischer83 are you using https://github.com/aspnetboilerplate/module-zero-core-template ? If so,
 we can update it's angular version as well.

**Comment by faithfulme** [comment] 2018-04-14 17:08
I use AspNetZero. Although Angular 5.2.9 is used, I still encounter the same problem. Any news?

**Comment by ezra2310** [comment] 2018-06-27 10:59
@Angular 6 also im getting same error. Menawhile i updated abp package with lastest one but still getting error while doing 'ng build'

Can you please help me how to fix the error and make build? My application can't able to run im seeking urgent for solution

> ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
> Module build failed: Error: F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
>     at plugin.done.then (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>

**Comment by brunobertechini** [comment] 2018-09-19 03:29
Same "hacked"  solution rather than a fix.

Feeling sad that no one is really willing to solve this

Bruno

**Comment by Worthy7** [comment] 2018-09-19 03:36
@brunobertechini  You can always PR :)

**Comment by ismcagdas** [comment] 2018-09-19 11:09
@brunobertechini this is the only solution I can find to this problem. I also don't think it is a wrong usage of importing ts files as mentioned in many issues in angular-cli repository. 

If you have a solution to the problem, we can try it as well.
